config/routes.rb
Rails.application.routes.draw do

  resources :friendships
  resources :events
  resources :story_members
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"

  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/' => 'users#index', :as => :users_index
  get 'users/' => 'users#home', :as => :users_home

  resources :stories, controller: "stories", only: [:create, :show]

  root 'users#home'

end

app/models/user.rb
class User < ApplicationRecord
	include Clearance::User

	mount_uploader :profilepic, ImageUploader

	validates :email, presence: {message: "Please fill-in all fields" }
	validates :email, uniqueness: { message: "must be new"}
	validates :email, format: { with: /\w*@.*\.\w*/, message: "Invalid email address" }
	validates :password, length: { minimum: 6, message: "Password must be at least 6 characters" }, on: :create

	has_many :stories, dependent: :destroy
  	has_many :events, dependent: :destroy
	has_many :friendships, dependent: :destroy
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user
	has_many :story_members
# In app/models/user.rb
	class User < ApplicationRecord
	    has_many :authentications, dependent: :destroy

	    def self.create_with_auth_and_hash(authentication, auth_hash)
	      user = self.create!(
	        name: auth_hash["name"],
	        email: auth_hash["extra"]["raw_info"]["email"]
	      )
	      user.authentications << authentication
	      return user
	    end

	    # grab fb_token to access Facebook for user data
	    def fb_token
	      x = self.authentications.find_by(provider: 'facebook')
	      return x.token unless x.nil?
	    end
	 end

	 def self.search(search)
		 if search
			 where("first_name ILIKE ?", "%#{search}%") || where("last_name ILIKE ?", "%#{search}%")
		 end
	 end
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params
    # date = User.datetime('/upload/20160424_174952.jpg')
    # long = User.longitude('/upload/20160424_174952.jpg')
    # lat = User.latitude('/upload/20160424_174952.jpg')
    # @user.update(datetime: date, longitude: long, latitude: lat)

    if @user.save
      sign_in @user
      redirect_to users_index_path
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
      email = user_params.delete(:email)
      password = user_params.delete(:password)
      first_name = user_params.delete(:first_name)
      last_name = user_params.delete(:last_name)
      profilepic = user_params.delete(:profilepic)

      Clearance.configuration.user_model.new(user_params).tap do |user|
        user.email = email
        user.password = password
        user.first_name = first_name
        user.last_name = last_name
        user.profilepic = profilepic
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json

  def home
    @user = User.all

  end

  def index

    @users = User.all
    @searched_users = User.search(params[:search])
    @stories = Story.search(params[:search])
    # @events = Event.search(params[:search])
    # @users = User.search(params[:search])
    # @results = @stories + @events + @users
    # + Event.search(params[:search]) + User.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end


  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @friend = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
    if current_user == User.find(params[:id])
       @user = current_user
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, type: 'first_name' %>
</div>

<div class="text-field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name, type: 'last_name' %>
</div>

<div>
  <label for="profilepic">Profile Picture</label>
  <%= form.file_field :profilepic %>
</div>

app/views/users/_search_result.html.erb
      <% if @stories.present? %>
        <% @stories.each do |story| %>
            <%= link_to story_path(story.id) do %>
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="pmd-card pmd-card-default pmd-z-depth" style="margin: 10px;">

                        <!-- Card media -->
                        <div class="pmd-card-media">
                   <%=image_tag story.photo.card.url, class:"img-responsive", id:"card-photo"%>
                        </div>

                        <!-- Card header -->
                        <div class="pmd-card-title" style="text-decoration: none;">
                            <h2 class="pmd-card-title-text" style="font-size: 20px;"><%= story.title.upcase %></h2>
                            <span class="pmd-card-subtitle-text"><%= story.description.capitalize %></span>
                        </div>
                    </div>
                </div>
            <% end %>
          <% end %>
          <% else %>
          <p> no result </p>
          <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<!-- Nav menu -->
<nav class="navbar navbar-inverse pmd-navbar navbar-fixed-top pmd-z-depth" style="background-color: transparent; border-color: transparent; box-shadow: none;" >
  <div class="container-fluid">
      <!-- Sidebar Toggle Button-->
      <div class="navbar-header">
          <a class="btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary pull-left margin-r8 pmd-sidebar-toggle" id='navbar-icons-menu'><i class="material-icons" style="color: #5DBCD2; text-shadow: 1px 1px 1px rgba(0,0,0,0.3);">menu</i></a>
          <!-- BRANDING LOCATION-->
          <%= link_to root_path do %><span class="navbar-brand" style="color: #5DBCD2; text-shadow: 1px 1px 1px rgba(0,0,0,0.3);">Xplor</span> <% end %>

      </div>

      <!-- Navbar Right icon (Search) open up hidden search box -->
      <div class="pmd-navbar-right-icon pull-right">
          <a class="btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary" id='navbar-search-container' onclick="clickShow('log-in')"><i class="material-icons pmd-sm" id='navbar-icons-search' style="color: #5DBCD2; text-shadow: 1px 1px 1px rgba(0,0,0,0.3);">search</i></a>
      </div>
  </div>
</nav>

<!-- Open sidebar -->
<section id="pmd-main">
  <!-- Left sidebar -->
  <aside class="pmd-sidebar sidebar-custom sidebar-default pmd-sidebar-slide-push pmd-sidebar-left pmd-z-depth sidebar-hide-custom" role="navigation" style="position: absolute;">
      <ul class="nav pmd-sidebar-nav">
          <!-- My Account Info -->
          <li class="pmd-user-info">
            <%= link_to users_index_path do %>
              <div class="media-left">
                <% if signed_in? -%>
                  <!-- If Signed In Show Profile Pic Thumb -->
                  <% if current_user.profilepic.thumb.url != nil %>
                    <%=image_tag current_user.profilepic.thumb.url, class:"card-thumb"%>
                  <% else -%>
                  <!-- If Signed In But No Profile Pic Thumb Show Blank Profile Pic-->
                    <img width="40" height="40" alt="avatar" src="/assets/blank_profile_pic_Fotor1.png">
                  <% end -%>
                <% else -%>
                <!-- If Not Signed Show Blank Profile Pic-->
                  <img width="40" height="40" alt="avatar" src="/assets/blank_profile_pic_Fotor1.png">
                <% end -%>
              </div>
              <div class="media-body media-middle">
                <% if signed_in? -%>
                    <% if current_user.first_name != nil -%>
                       <!-- If Signed In Show Full Name -->
                      My Account: <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>
                    <% end -%>
                  <% else -%>
                    <!-- If Not Signed In Show Name is Guest -->
                    Guest
                  <% end -%>
              </div>
            <% end %>
          </li>

          <!-- Sidebar Link Items -->

            <!-- Link to ???? -->
            <% if signed_in? -%>
              <% if current_user.stories != nil %>
                <li class="pmd">
                  <%= link_to users_index_path do %>
                    <span class="media-body" style="font-size: 15px;">My Stories</span>
                  <% end %>
                <li>
                <% current_user.stories.each do |story| %>
                  <li class="pmd-ripple-effect">


                    <%= link_to story_path(story.id) do %>
                      <i class="material-icons media-left media-middle">book</i><span


                      class="media-body" style="font-size: 15px;"><%= story.title %></span>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            <% end %>

            <!-- Link to Log off if signed in -->
            <% if signed_in? -%>
              <li class="pmd-ripple-effect" style="position: absolute; bottom: 20px;">
                <%= link_to sign_out_path(@users), method: :delete do %><i class="material-icons media-left media-middle">exit_to_app</i> <span class="media-body" style="font-size: 15px;">Logout</span><% end %>
              </li>
            <% else %>
              <!-- Links to Log In or Sign up if not logged in Modals-->
              <li class="pmd-ripple-effect">
                <a data-target="#form-dialog" data-toggle="modal"><i class="material-icons media-left media-middle">exit_to_app</i> <span class="media-body" style="font-size: 15px;">Login</span></a>
              </li>
              <li class="pmd-ripple-effect">
                <a data-target="#form-dialog-signup" data-toggle="modal"><i class="material-icons media-left media-middle">exit_to_app</i> <span class="media-body" style="font-size: 15px;">Sign Up</span></a>
              </li>
            <% end %>
      </ul>
    </aside>


<div id="banner-home">

      <p id='brand'> Xplor </p>
      <p id='slogan'> record your Xploration </p>


      <div id="transbox">

        <%= form_for :session, url: session_path do |form| %>
            <!-- <label for="first-name">Email Address</label> -->
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                 <input type="text" placeholder="Email Address" class="form-control" name=session[email]>
            </div>
            <br>
            <!-- <label for="first-name">Password</label> -->
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                 <input type="password" placeholder ="Password" class="form-control" name=session[password]>
            </div>

            <div class="row">
                <div class="pmd-modal-action" id="login">
                    <div class="col-md-4">
                        <%= form.submit "Sign In", class: "pmd-ripple-effect btn btn-primary", id: "sign-in-button"%>
                    </div>
          <% end %>
                 <div class="col-md-4">
                      <a  id="sign-up-button" class="btn btn-primary" data-target="#form-dialog-signup" data-toggle="modal">Sign Up</a>
                 </div>
               </div>
            </div>

            <table width="100%">
              <td><hr /></td>
              <td style="width:1px; padding: 0 10px; white-space: nowrap; color: white;">OR</td>
              <td><hr /></td>
            </table>
            <br>
            <%= link_to "/auth/facebook" do %>
              <img id="fb_login" class=".pmd-z-depth-3" src="/assets/fblogin.png" alt="Log In With Facebook" height='40px'>
            <% end %>


      </div>

  <div class="text-center" style="padding-top: 60px;">
    <span style="color: white; font-size: 16px;"> Site Developed With: </span>
    <img style="width: 500px" src="/assets/emblem.png">
  </div>

</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
  <div id="profile-info" style="background-color: white; height: 2000px; width: 25%; box-shadow: 2px 2px 1px rgba(0,0,0,0.3); padding-right: 0px; padding-top: 50px; float: left;">
    <div style="width: 100%; background-color: #588C8B; margin-top: 0px; margin-bottom: 0px;">
      <h1 style="padding-left: 20px; padding-top: 15px; margin-top: 0px; margin-bottom: 0px;" class='text-center'><%= current_user.first_name %> <%= current_user.last_name %>'s Profile</h1>
    </div>
    <div class='text-center'>
      <% if current_user.profilepic.url != nil %>
        <%= image_tag current_user.profilepic.card.url, :style => "max-height: 400px; max-width: 100%;"%><br>
      <% end %>
    </div>
    <span style="font-size: 18px; padding-left: 10px;">Full Name: <%= current_user.first_name %> <%= current_user.last_name %></span><br>
    <span style="font-size: 18px; padding-left: 10px;">Email Address: <%= current_user.email %></span><br>
    <span style="font-size: 18px; padding-left: 10px;"><%= link_to edit_user_path(@users) do %> Edit Profile <% end %></span><br>
    <br>
    <div style="width: 100%; background-color: #588C8B;">
      <span style="font-size: 22px; color: black; padding-left: 10px;">Friends List</span><br>
    </div>
    <%= form_tag users_home_path, :method => 'get' do %>
      <p>
        <input type="text_field" placeholder="Search For Users" name="search">
        <%= submit_tag "Search", :name => nil %>
      </p>
    <% end %>
    <% if @searched_users.present?%>
      <% @searched_users.each do |x| %>
        <%= link_to x.first_name + " " + x.last_name, user_path(x.id) %><br>
      <% end %>
    <% end %>
    <% else %>

    <br>
    <span style="font-size: 18px; padding-left: 10px;">My Friends</span><br>
    <% for friendship in current_user.friendships %>
      <span style="font-size: 18px; padding-left: 10px;">
        <%= link_to user_path(friendship.friend.id) do %><%= friendship.friend.first_name %> <%= friendship.friend.last_name %><% end %>
      </span><br>
    <% end %>
  </div>



<div class="text-center" style="padding-top: 70px;">
  <%= form_tag users_index_path, :method => 'get', remote: true do %>
    <p>
      <input type="text_field" placeholder="Search My Stories" name="search">
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
</div>

<div class="text-center">
  <span style="font-size: 24px;">My Stories</span>
</div>

<div id="search_result">
<% if @stories.present? %>
<% @stories.each do |x| %>
  <%= x.title %>
  <% end %>
<% end %>
</div>

<div id="all_content" class="row">
    <!-- Media, Title, and Description area -->
    <% if signed_in? %>
        <% if current_user.stories != nil %>
            <% count = current_user.stories.count %>
            <div class="col-sm-4" style="padding: 5px 2px 2px 2px;">
              <% current_user.stories.each_with_index do |story, index| %>
                <% modulus = index % 2 %>
                  <% if modulus == 0 %> 
                      <%= link_to story_path(story.id) do %>
                        <div class="pmd-card pmd-card-default pmd-z-depth" style="margin: 2px;">

                            <!-- Card media -->
                            <div class="pmd-card-media">
                              <%=image_tag story.photo.card.url, class:"img-responsive", id:"card-photo"%>
                            </div>

                            <!-- Card header -->
                            <div class="pmd-card-title" style="text-decoration: none;">
                              <h2 class="pmd-card-title-text" style="font-size: 20px;"><%= story.title.upcase %></h2>
                              <span class="pmd-card-subtitle-text"><%= story.description.capitalize %></span>
                            </div>
                        </div>
                      <% end %>
                  <% end %>
              <% end %>
            </div>

            <div class="col-sm-4" style="padding: 5px 2px 2px 2px;">
              <% current_user.stories.each_with_index do |story, index| %>
                <% modulus = index % 2 %>
                  <% if modulus == 1 %> 
                      <%= link_to story_path(story.id) do %>
                        <div class="pmd-card pmd-card-default pmd-z-depth" style="margin: 2px;">

                            <!-- Card media -->
                            <div class="pmd-card-media">
                              <%=image_tag story.photo.card.url, class:"img-responsive", id:"card-photo"%>
                            </div>

                            <!-- Card header -->
                            <div class="pmd-card-title" style="text-decoration: none;">
                              <h2 class="pmd-card-title-text" style="font-size: 20px;"><%= story.title.upcase %></h2>
                              <span class="pmd-card-subtitle-text"><%= story.description.capitalize %></span>
                            </div>
                        </div>
                      <% end %>
                  <% end %>
              <% end %>
            </div>
        <% end %>
    <% end %>

</div>

<!-- New Story Modal -->
<div tabindex="-1" class="modal fade" id="form-dialog-story" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header pmd-modal-bordered">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
        <h2 class="pmd-card-title-text">Make A New Travel Story</h2><!-- Title -->
      </div>
      <%= form_for :story, url: stories_path do |form| %>
      <div class="modal-body">
        <div class="form-group pmd-textfield pmd-textfield-floating-label">
          <label for="Title">Title</label>
          <input type="text" class="mat-input form-control" name=story[title]>
        </div>
        <div class="form-group pmd-textfield pmd-textfield-floating-label">
          <label for="description">Description</label>
          <input type="text" class="mat-input form-control" name=story[description]>
        </div>
        <div class="form-group pmd-textfield">
          <label for="photo">Story Photo</label>
          <%= form.file_field :photo %>
        </div>
      </div>
      <div class="pmd-modal-action">
        <%= form.submit :Submit, class: 'btn pmd-ripple-effect btn-primary' %>
      </div>
      <%end%>
    </div>
  </div>
</div>



<!-- Lower Left raised circle button with ripple effect -->
<div class="pmd-floating-action"  role="navigation" style="z-index: 1001;">
  <a data-target="#form-dialog-story" data-toggle="modal" class="pmd-floating-action-btn btn pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-primary" data-title="New Travel Story">
    <span class="pmd-floating-hidden">New Travel Story</span>
    <i class="material-icons pmd-sm">add</i>
  </a>
</div>

app/views/users/index.js.erb
$('#search_result').html('')
$('#all_content').html('')
$('#search_result').prepend('<%=  escape_javascript(render :partial => 'search_result.html.erb', :locals => {stories: @stories}) %>')

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="text-field">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email' %>
    </div>

    <div class="password-field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p id="notice"><%= notice %></p>
  <div id="profile-info" style="background-color: white; height: 1000px; width: 25%; box-shadow: 2px 2px 1px rgba(0,0,0,0.3); padding-right: 0px; padding-top: 43px; float: left;">
    <div style="width: 100%; background-color: #588C8B; margin-top: 0px; margin-bottom: 0px;">
      <h1 style="padding-left: 20px; padding-top: 15px; margin-top: 0px; margin-bottom: 0px;" class='text-center'><%= @user.first_name %> <%= @user.last_name %>'s Profile</h1>
    </div>
    <div class='text-center'>
      <% if @user.profilepic.url != nil %>
        <%= image_tag @user.profilepic.card.url, :style => "max-height: 400px; max-width: 100%;"%><br>
      <% end %>
    </div>
    <span style="font-size: 18px; padding-left: 10px;">Full Name: <%= @user.first_name %> <%= @user.last_name %></span><br>
    <span style="font-size: 18px; padding-left: 10px;">Email Address: <%= @user.email %></span><br>
    <br>
	<span style="font-size: 18px; padding-left: 10px;"><%= link_to "Add Friend", friendships_path(:friend_id => @friend.id), :method => :post %></span>

<div id="search_result">

    <div style="width: 100%; background-color: #588C8B;">
      <span style="font-size: 22px; color: black; padding-left: 10px;">Friends List</span><br>
    </div>
    <% for friendship in @user.friendships %>
      <span style="font-size: 18px; padding-left: 10px;">
        <%= link_to user_path(friendship.friend.id) do %><%= friendship.friend.first_name %> <%= friendship.friend.last_name %><% end %>
      </span><br>
    <% end %>
  </div>






<div id="all_content" class="row">

    <!-- Media, Title, and Description area -->
    <% if signed_in? %>
        <% if @user.stories != nil %>
            <% count = @user.stories.count %>
            <% @user.stories.each do |story| %>
                <%= link_to story_path(story.id) do %>
                    <div class="col-sm-4" style="padding: 15px 2px 2px 2px;">
                        <div class="pmd-card pmd-card-default pmd-z-depth" style="margin: 2px;">

                            <!-- Card media -->
                            <div class="pmd-card-media">
                              <%=image_tag story.photo.card.url, class:"img-responsive", id:"card-photo"%>
                            </div>

                            <!-- Card header -->
                            <div class="pmd-card-title" style="text-decoration: none;">
                              <h2 class="pmd-card-title-text" style="font-size: 20px;"><%= story.title.upcase %></h2>
                              <span class="pmd-card-subtitle-text"><%= story.description.capitalize %></span>
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    <% end %>

</div>

<!-- New Story Modal -->
<div tabindex="-1" class="modal fade" id="form-dialog-story" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header pmd-modal-bordered">
        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
        <h2 class="pmd-card-title-text">Make A New Travel Story</h2><!-- Title -->
      </div>
      <%= form_for :story, url: stories_path do |form| %>
      <div class="modal-body">
        <div class="form-group pmd-textfield pmd-textfield-floating-label">
          <label for="Title">Title</label>
          <input type="text" class="mat-input form-control" name=story[title]>
        </div>
        <div class="form-group pmd-textfield pmd-textfield-floating-label">
          <label for="description">Description</label>
          <input type="text" class="mat-input form-control" name=story[description]>
        </div>
        <div class="form-group pmd-textfield">
          <label for="photo">Story Photo</label>
          <%= form.file_field :photo %>
        </div>
      </div>
      <div class="pmd-modal-action">
        <%= form.submit :Submit, class: 'btn pmd-ripple-effect btn-primary' %>
      </div>
      <%end%>
    </div>
  </div>
</div>



<!-- Lower Left raised circle button with ripple effect -->
<div class="pmd-floating-action"  role="navigation" style="z-index: 1001;">
  <a data-target="#form-dialog-story" data-toggle="modal" class="pmd-floating-action-btn btn pmd-btn-fab pmd-btn-raised pmd-ripple-effect btn-primary" data-title="New Travel Story">
    <span class="pmd-floating-hidden">New Travel Story</span>
    <i class="material-icons pmd-sm">add</i>
  </a>
</div>