config/routes.rb
Rails.application.routes.draw do

  resources :friendships
  resources :events
  resources :story_members
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"

  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/' => 'users#index', :as => :users_index
  get 'users/' => 'users#home', :as => :users_home

  resources :stories, controller: "stories", only: [:create, :show]

  root 'users#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
  class Authentication < ApplicationRecord
     belongs_to :user

     def self.create_with_omniauth(auth_hash)
       self.new(
         provider: auth_hash["provider"],
         uid: auth_hash["uid"],
         token: auth_hash["credentials"]["token"]
       )
     end

     def update_token(auth_hash)
       self.token = auth_hash["credentials"]["token"]
       self.save
     end
  end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :story
  has_many :eventphotos, dependent: :destroy
  accepts_nested_attributes_for :eventphotos

  def self.search(search)
    if search
      where("what ILIKE ?", "%#{search}%")
    end
  end
end

app/models/event_member.rb
class EventMember < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/eventphoto.rb
class Eventphoto < ApplicationRecord
	belongs_to :event
	mount_uploader :photo, ImageUploader

	def self.datetime(img_file)
		if Exif::Data.new(img_file).date_time != nil
			data = Exif::Data.new(img_file)
			datetime = data.date_time
		else
			datetime = nil
		end

		return datetime	
	end

	def self.latitude(img_file)
		if Exif::Data.new(img_file).gps_latitude != nil 
		data = Exif::Data.new(img_file) 
		latitude = data.gps_latitude
			if data.gps_latitude_ref == "S"
				latitude = (-1) * latitude
			end
		else
			latitude = nil
		end
		
		return latitude
	end

	def self.longitude(img_file)
		if Exif::Data.new(img_file).gps_longitude != nil 
		data = Exif::Data.new(img_file) 
		longitude = data.gps_longitude
			if data.gps_longitude_ref == "W"
				longitude = (-1) * longitude
			end
		else
			longitude = nil
		end
		
		return longitude
	end

end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/photo.rb
class Photo < ApplicationRecord
	def datetime(img_file)
		data = Exif::Data.new('img_file')
		return datetime = data.date_time	
	end

	def latitude(img_file)
		data = Exif::Data.new('img_file')
		return datetime = data.gps_latitude	
	end

	def longitude(img_file)
		data = Exif::Data.new('img_file')
		return datetime = data.gps_longitude
	end	
end

app/models/story_member.rb
class StoryMember < ApplicationRecord
  belongs_to :user
  belongs_to :story
end

app/models/user.rb
class User < ApplicationRecord
	include Clearance::User

	mount_uploader :profilepic, ImageUploader

	validates :email, presence: {message: "Please fill-in all fields" }
	validates :email, uniqueness: { message: "must be new"}
	validates :email, format: { with: /\w*@.*\.\w*/, message: "Invalid email address" }
	validates :password, length: { minimum: 6, message: "Password must be at least 6 characters" }, on: :create

	has_many :stories, dependent: :destroy
  	has_many :events, dependent: :destroy
	has_many :friendships, dependent: :destroy
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user
	has_many :story_members
# In app/models/user.rb
	class User < ApplicationRecord
	    has_many :authentications, dependent: :destroy

	    def self.create_with_auth_and_hash(authentication, auth_hash)
	      user = self.create!(
	        name: auth_hash["name"],
	        email: auth_hash["extra"]["raw_info"]["email"]
	      )
	      user.authentications << authentication
	      return user
	    end

	    # grab fb_token to access Facebook for user data
	    def fb_token
	      x = self.authentications.find_by(provider: 'facebook')
	      return x.token unless x.nil?
	    end
	 end

	 def self.search(search)
		 if search
			 where("first_name ILIKE ?", "%#{search}%") || where("last_name ILIKE ?", "%#{search}%")
		 end
	 end
end

app/controllers/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :story_members, dependent: :destroy
  mount_uploader :photo, ImageUploader

  def self.search(search)
    if search
      where("title ILIKE ?", "%#{search}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json

  def home
    @user = User.all

  end

  def index

    @users = User.all
    @searched_users = User.search(params[:search])
    @stories = Story.search(params[:search])
    # @events = Event.search(params[:search])
    # @users = User.search(params[:search])
    # @results = @stories + @events + @users
    # + Event.search(params[:search]) + User.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end


  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @friend = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
    if current_user == User.find(params[:id])
       @user = current_user
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventphotos_helper.rb
module EventphotosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/story_member_helpers.rb
module StoryMemberHelper
end

app/helpers/story_members_helper.rb
module StoryMembersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>

<!-- Basic fixed sidebar -->

<!-- Nav menu -->
<nav class="navbar navbar-inverse pmd-navbar navbar-fixed-top pmd-z-depth">
  <div class="container-fluid">
      <!-- Sidebar Toggle Button-->
      <div class="navbar-header">
          <a class="btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary pull-left margin-r8 pmd-sidebar-toggle" id='navbar-icons-menu'><i class="material-icons">menu</i></a>
          <!-- BRANDING LOCATION-->
          <%= link_to users_index_path do %><span class="navbar-brand" style="color: #EAE7DC; text-shadow: 1px 1px 1px rgba(0,0,0,0.3);">Xplor</span> <% end %>

      </div>

      <!-- Navbar Right icon (Search) open up hidden search box -->
      <div class="pmd-navbar-right-icon pull-right">
          <a class="btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary" id='navbar-search-container' onclick="clickShow('log-in')"><i class="material-icons pmd-sm" id='navbar-icons-search'>search</i></a>
      </div>
  </div>
</nav>

<!-- Open sidebar -->
<section id="pmd-main">
  <!-- Left sidebar -->
  <aside class="pmd-sidebar sidebar-custom sidebar-default pmd-sidebar-slide-push pmd-sidebar-left pmd-z-depth sidebar-hide-custom" role="navigation">
      <ul class="nav pmd-sidebar-nav">
          <!-- My Account Info -->
          <li class="pmd-user-info">
            <%= link_to users_index_path do %>
              <div class="media-left">
                <% if signed_in? -%>
                  <!-- If Signed In Show Profile Pic Thumb -->
                  <% if current_user.profilepic.thumb.url != nil %>
                    <%=image_tag current_user.profilepic.thumb.url, class:"card-thumb"%>
                  <% else -%>
                  <!-- If Signed In But No Profile Pic Thumb Show Blank Profile Pic-->
                    <img width="40" height="40" alt="avatar" src="/assets/blank_profile_pic_Fotor1.png">
                  <% end -%>
                <% else -%>
                <!-- If Not Signed Show Blank Profile Pic-->
                  <img width="40" height="40" alt="avatar" src="/assets/blank_profile_pic_Fotor1.png">
                <% end -%>
              </div>
              <div class="media-body media-middle">
                <% if signed_in? -%>
                    <% if current_user.first_name != nil -%>
                       <!-- If Signed In Show Full Name -->
                      My Account: <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>
                    <% end -%>
                  <% else -%>
                    <!-- If Not Signed In Show Name is Guest -->
                    Guest
                  <% end -%>
              </div>
            <% end %>
          </li>

          <!-- Sidebar Link Items -->

            <!-- Link to ???? -->
            <% if signed_in? -%>
              <% if current_user.stories != nil %>
                <li class="pmd">
                  <%= link_to users_index_path do %>
                    <span class="media-body" style="font-size: 15px;">My Stories</span>
                  <% end %>
                <li>
                <% current_user.stories.each do |story| %>
                  <li class="pmd-ripple-effect">

                    <%= link_to story_path(story.id) do %>
                      <i class="material-icons media-left media-middle">book</i><span
                      class="media-body" style="font-size: 15px;"><%= story.title %></span>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            <% end %>

            <!-- Link to Log off if signed in -->
            <% if signed_in? -%>
              <li class="pmd-ripple-effect" style="position: absolute; bottom: 20px;">
                <%= link_to sign_out_path(@users), method: :delete do %><i class="material-icons media-left media-middle">exit_to_app</i> <span class="media-body" style="font-size: 15px;">Logout</span><% end %>
              </li>
            <% else %>
              <!-- Links to Log In or Sign up if not logged in Modals-->
              <li class="pmd-ripple-effect">
                <a data-target="#form-dialog" data-toggle="modal"><i class="material-icons media-left media-middle">exit_to_app</i> <span class="media-body" style="font-size: 15px;">Login</span></a>
              </li>
              <li class="pmd-ripple-effect">
                <a data-target="#form-dialog-signup" data-toggle="modal"><i class="material-icons media-left media-middle">exit_to_app</i> <span class="media-body" style="font-size: 15px;">Sign Up</span></a>
              </li>
            <% end %>
      </ul>
    </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Xplor</title>
  <%= favicon_link_tag 'logomakr.png' %>
	<%= csrf_meta_tag %>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="http://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

	<%= stylesheet_link_tag 'application' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </head>
  <body>
  	    <!-- <%# if signed_in? %>
      Signed in as: <%#= current_user.email %>
      <%#= button_to 'Sign out', sign_out_path, method: :delete %>
    <%# else %>
      <%#= link_to 'Sign in', sign_in_path %>
    <%# end %>
 -->
     <!-- <div id="flash">
      <%# flash.each do |key, value| %>
        <div class="flash <%#= key %>"><%#= value %></div>
      <%# end %>
    </div> -->
<% unless action_name == "home" %>
   <%= render partial: "layouts/navbar" %>
<% end %>

    <!-- Log In Modal -->
    <div tabindex="-1" class="modal fade" id="form-dialog" style="display: none;" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header pmd-modal-bordered">
            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
            <h2 class="pmd-card-title-text">Log In</h2><!-- Title -->
          </div>
          <%= form_for :session, url: session_path do |form| %>
          <div class="modal-body">
            <div class="form-group pmd-textfield pmd-textfield-floating-label">
              <label for="first-name">Email Address</label>
              <input type="text" class="mat-input form-control" name=session[email]>
            </div>
            <div class="form-group pmd-textfield pmd-textfield-floating-label">
              <label for="first-name">Password</label>
              <input type="password" class="mat-input form-control" name=session[password]>
            </div>

          </div>
          <div class="pmd-modal-action">
            <%= form.submit do%><button data-dismiss="modal"  class="btn pmd-ripple-effect btn-primary" type="button">Log In</button><% end %>
            <%= link_to "/auth/facebook" do %>
              <img id="facebook_login" class=".pmd-z-depth-3" src="/assets/facebook_login.png" alt="Sign In With Facebook" height='40px'>
            <% end %>
          </div>
          <%end%>
        </div>
      </div>
    </div>

    <!-- Sign Up Modal -->
    <div tabindex="-1" class="modal fade" id="form-dialog-signup" style="display: none;" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header pmd-modal-bordered">
            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
            <h2 class="pmd-card-title-text">Sign Up</h2><!-- Title -->
          </div>
          <%= form_for :user, url: users_path do |form| %>
          <div class="modal-body">
            <div class="form-group pmd-textfield pmd-textfield-floating-label">
              <label for="first-name">First Name</label>
              <input type="text" class="mat-input form-control" name=user[first_name]>
            </div>
            <div class="form-group pmd-textfield pmd-textfield-floating-label">
              <label for="last-name">Last Name</label>
              <input type="text" class="mat-input form-control" name=user[last_name]>
            </div>
            <div class="form-group pmd-textfield pmd-textfield-floating-label">
              <label for="email">Email Address</label>
              <input type="text" class="mat-input form-control" name=user[email]>
            </div>
            <div>
              <label for="profilepic">Profile Picture</label>
              <%= form.file_field :profilepic %>
            </div>
            <div class="form-group pmd-textfield pmd-textfield-floating-label">
              <label for="first-name">Password</label>
              <input type="password" class="mat-input form-control" name=user[password]>
            </div>
            <label class="checkbox-inline pmd-checkbox pmd-checkbox-ripple-effect">
              <input type="checkbox" value="">
              <span class="pmd-checkbox"> Accept Terms and conditions</span>
            </label>
          </div>
          <div class="pmd-modal-action">
            <%= form.submit :Submit, class: 'btn pmd-ripple-effect btn-primary' %>
            <%= link_to "/auth/facebook" do %>
              <img id="facebook_login" class=".pmd-z-depth-3" src="/assets/facebook_login.png" alt="Sign In With Facebook" height='40px'>
            <% end %>
          </div>
          <%end%>
        </div>
      </div>
    </div>

    <%= yield %>

  <div class="pmd-sidebar-overlay"></div>
</section>

  </body>
</html>